"""
Known Canadian grocery brand names to strip from product names during barcode scanning.

Used in openfood.py to clean product names before ingredient matching. OpenFoodFacts
provides a `brands` field but it is crowd-sourced and unreliable — this list is a
fallback for brands that are common in Canadian grocery stores.

Brand names are stored lowercase for case-insensitive matching.
Only include brand names that would otherwise interfere with ingredient matching
(e.g. "Butterball Turkey Bacon" → "butterball" must be removed to match "bacon").
"""

CANADIAN_GROCERY_BRANDS: set[str] = {
    # ── Poultry & Meat ────────────────────────────────────────────────────────
    "butterball",
    "maple leaf",
    "schneiders",
    "mitchells",
    "olymel",
    "premium",        # "Premium" appears as a Maple Leaf sub-brand
    "lafleur",
    "hygrade",
    "harvest",

    # ── Dairy ─────────────────────────────────────────────────────────────────
    "gay lea",
    "natrel",
    "beatrice",
    "neilson",
    "organic meadow",
    "armstrong",
    "black diamond",
    "balderson",
    "ivanhoe",
    "lactantia",
    "island farms",
    "dairyland",
    "saputo",
    "baxter",
    "filion",

    # ── Bread & Bakery ────────────────────────────────────────────────────────
    "dempsters",
    "dempster's",
    "wonder",
    "villaggio",
    "stonemill",
    "silver hills",
    "canada bread",
    "weston",
    "d'italiano",
    "italian home",

    # ── Snacks & Cereal ───────────────────────────────────────────────────────
    "dare",
    "vachon",
    "leclerc",
    "voortman",
    "mccain",
    "hostess",

    # ── Beverages ─────────────────────────────────────────────────────────────
    "president's choice",
    "presidents choice",
    "pc",
    "compliments",
    "selection",        # Metro house brand
    "our finest",
    "equality",
    "irresistibles",
    "life smart",

    # ── National / Cross-border brands common in CA ───────────────────────────
    "kraft",
    "heinz",
    "campbell's",
    "campbells",
    "hunts",
    "hunt's",
    "general mills",
    "kellogg's",
    "kelloggs",
    "quaker",
    "pillsbury",
    "robin hood",
    "five roses",
    "catelli",
    "barilla",
    "classico",
    "ragu",
    "bertolli",
    "uncle ben's",
    "uncle bens",
    "ben's original",
    "knorr",
    "maggi",
    "lipton",
    "tetley",
    "red rose",
    "celestial seasonings",
    "mccormick",
    "club house",
    "french's",
    "frenchs",
    "lea & perrins",
    "lea and perrins",
    "heinz",
    "hellmann's",
    "hellmanns",
    "miracle whip",
    "skippy",
    "jif",
    "smucker's",
    "smuckers",
    "crisco",
    "parkay",
    "becel",
    "fleischmann's",
    "fleischmanns",
    "philadelphia",
    "cheez whiz",
    "velveeta",
    "cracker barrel",
    "oreo",
    "christie",
    "chips ahoy",
    "ritz",
    "triscuit",
    "wheat thins",
    "premium plus",
    "breton",
    "stacy's",
    "lay's",
    "lays",
    "pringles",
    "doritos",
    "cheetos",
    "ruffles",
    "old dutch",
    "humpty dumpty",
    "wise",
    "ben & jerry's",
    "häagen-dazs",
    "haagen-dazs",
    "breyers",
    "chapmans",
    "chapman's",
    "nestlé",
    "nestle",
    "gerber",
    "heinz baby",
    "tropicana",
    "minute maid",
    "ocean spray",
    "welch's",
    "welchs",
    "dole",
    "del monte",
    "green giant",
    "birds eye",
    "bird's eye",
    "mccain",
    "cavendish",
    "ore-ida",
}
