"""update recipe models to uuid and add substitutions

Revision ID: 953c8611f8bf
Revises: 201d713f6139
Create Date: 2026-02-13 03:30:03.809770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953c8611f8bf'
down_revision: Union[str, Sequence[str], None] = '201d713f6139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_substitutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('substitute_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['original_ingredient_id'], ['ingredient_references.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_ingredient_id'], ['ingredient_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_substitutions_id'), 'ingredient_substitutions', ['id'], unique=False)
    op.alter_column('ingredient_aliases', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ingredient_aliases', 'ingredient_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_ingredient_aliases_id'), 'ingredient_aliases', ['id'], unique=False)
    op.alter_column('ingredient_references', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'recipe_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'canonical_ingredient_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('recipe_ingredients', 'canonical_ingredient_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'recipe_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('ingredient_references', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_ingredient_aliases_id'), table_name='ingredient_aliases')
    op.alter_column('ingredient_aliases', 'ingredient_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ingredient_aliases', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_ingredient_substitutions_id'), table_name='ingredient_substitutions')
    op.drop_table('ingredient_substitutions')
    # ### end Alembic commands ###
