"""initial schema with uuid models

Revision ID: d36a07b2efef
Revises: 
Create Date: 2026-02-13 05:41:19.544175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd36a07b2efef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_references_id'), 'ingredient_references', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_references_name'), 'ingredient_references', ['name'], unique=True)
    op.create_index(op.f('ix_ingredient_references_normalized_name'), 'ingredient_references', ['normalized_name'], unique=False)
    op.create_table('product_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('brands', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('package_quantity', sa.Float(), nullable=True),
    sa.Column('package_unit', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_references_barcode'), 'product_references', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_references_id'), 'product_references', ['id'], unique=False)
    op.create_index(op.f('ix_product_references_name'), 'product_references', ['name'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('instructions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_aliases_alias'), 'ingredient_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_ingredient_aliases_id'), 'ingredient_aliases', ['id'], unique=False)
    op.create_table('ingredient_substitutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('substitute_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['original_ingredient_id'], ['ingredient_references.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_ingredient_id'], ['ingredient_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_substitutions_id'), 'ingredient_substitutions', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_reference_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.Enum('FRIDGE', 'FREEZER', 'CUPBOARD', name='locations'), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_reference_id'], ['product_references.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_reference_id', 'location', name='_product_location_uc')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_text', sa.String(), nullable=False),
    sa.Column('canonical_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_ingredient_id'], ['ingredient_references.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_ingredient_substitutions_id'), table_name='ingredient_substitutions')
    op.drop_table('ingredient_substitutions')
    op.drop_index(op.f('ix_ingredient_aliases_id'), table_name='ingredient_aliases')
    op.drop_index(op.f('ix_ingredient_aliases_alias'), table_name='ingredient_aliases')
    op.drop_table('ingredient_aliases')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_product_references_name'), table_name='product_references')
    op.drop_index(op.f('ix_product_references_id'), table_name='product_references')
    op.drop_index(op.f('ix_product_references_barcode'), table_name='product_references')
    op.drop_table('product_references')
    op.drop_index(op.f('ix_ingredient_references_normalized_name'), table_name='ingredient_references')
    op.drop_index(op.f('ix_ingredient_references_name'), table_name='ingredient_references')
    op.drop_index(op.f('ix_ingredient_references_id'), table_name='ingredient_references')
    op.drop_table('ingredient_references')
    # ### end Alembic commands ###
